name: nnrf-nfm-newrelease
on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APPLICATIONENV: fakenrf-env
  BRANCH: master
  WORKFLOW: nnrf-nfm-newversion

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add TAG_NAME env property
        run:  echo "TAG_NAME=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV
      - name: Open PR in Environment Repository for new App Version
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/${{ env.APPLICATIONENV }}
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.TOKEN }}
          inputs: '{"tag_name": "${{ env.TAG_NAME }}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ env.REGISTRY }}/${{ github.event.repository.full_name }}:${{ env.TAG_NAME }}"}'
          ref: refs/heads/${{ env.BRANCH }}
          repo: ${{ env.ENV_REPO }}
